#define Mes1 "<Hand>#<Ручное>"
#define Mes5 "Num zones=#Кол-во зон="
#define Mes6 "From#с"
#define Mes7 "Zone#Зона"
#define Mes10 "Alarm"
#define Mes13 "Pause#Пауза"
#define Mes19 "Task N#Задание N"
#define Mes34 "Climate task#Задания климата"
#define Mes35 "Timer #Задание "
//#define Mes36 "Measure #Измерено "
//#define Mes37 "Task #Задано "
#define Mes38 "Conditions#Состояние"
#define Mes39 "Heating (measure then task)#Отопление (измерено ниже задано)"
#define Mes40 "Theat=#Tотоп="
#define Mes41 "Tvent=#Tвент="
#define Mes42 "Treal=#Tреал="
#define Mes43 "RHtask=#RHзад="
#define Mes44 "RHreal=#RHреал="
#define Mes45 "COtask=#COзад="
#define Mes46 "CO2real=#CO2реал="
#define Mes65 "Access code=#Код доступа="
#define Mes66 "Init Tasks=#Сброс заданий="
#define Mes67 "Init Calibrations=#Сброс калибровок="
#define Mes68 "Init Parameters=#Сброс параметров="
#define Mes69 "Init Configuration=#Сброс конфигурации="
#define Mes70 "Time=#Время="
#define Mes71 "Date=#Дата="
#define Mes72 "Strategy of control#Стратегия управления"
#define Mes73 "Important on heat=#Важность в нагреве="
#define Mes74 "RH influence=#Влияние влажности="
#define Mes75 "Optimal influence=#Влияние оптимума="
#define Mes76 "Heating pipe #Контур "
#define Mes85 "Parameters#Параметры управления"
#define Mes86 "-Configuration-#--Конфигурация--"
#define Mes87 "-output#-выход"
#define Mes88 "-input#-вход"
#define Mes89 "-end of parameters-#-конец списка-"
#define Mes90 "-Parameters-#-Параметры-"
#define Mes91 "-Tuning-#-Настройка-"
#define Mes92 "Setting #Уставка "
#define Mes96 "sec#сек"
#define Mes97 "P-band=#П-коэф="
#define Mes98 "I-band=#Б-коэф="
#define Mes99 "Type=#Тип="
#define Mes126 "Controller num=#Номер контроллера="
#define Mes127 "Language=#Язык="
#define Mes128 "Manual control#Ручное управление"
#define Mes133 "Position=#Состояние="
#define Mes134 "Mode=#Режим="
#define Mes135 "Working time=#Время работы="
#define Mes136 "Closing#Закрытие"
#define Mes137 "Opening"
#define Mes138 "(auto)#(авто)"
#define	Mes139 "(manual)#(ручное)"
#define Mes140 "Output#Выход"
#define Mes144 "<digital>#<цифровой>"
#define Mes145 "No sensor#Нет датчика"
#define Mes146 "Multi sensor#Есть датчики"
#define Mes147 "Port tuning#Настройка порта"
#define Mes148 "Sensor calibration#Калибровка датчиков"
#define Mes149 "Type #Тип "
#define Mes150 "mV#мВ"
#define Mes151 "Frequency=#Частота="
#define Mes152 "Factor=# Коэф="
#define Mes153 "Port=#Порт="
#define Mes154 "Point1:#Точка 1:"
#define Mes155 "Point2:#Точка 2:"
#define Mes156 " corr # корр "
#define Mes157 " out # вых "
#define Mes158 "Volt=#Напр="
#define Mes159 "Meteo#Метео"
#define Mes206 "Screensaver=#Заставка="
#define Mes211 "Mechanic settings#Параметры механизмов"
#define Mes221 "<Input 1 for init>#<Ввод 1 для сброса>"
#define Mes222 "Init Strategy=#Сброс стратегии="
#define Mes223 "Version#Версия"


